CHIP_FAMILY = samd51
CHIP_VARIANT = SAMD51J20A
CUSTOM_CFLAGS =
#CUSTOM_CFLAGS += -DUSE_MSC=1
CUSTOM_CFLAGS += -DUSE_UART=1
CUSTOM_CFLAGS += -DUSE_LOGS=1
#CUSTOM_CFLAGS += -DUSE_FAT=1
#CUSTOM_CFLAGS += -DUSE_INDEX_HTM=1